ALTER TABLE fish
ADD COLUMN IF NOT EXISTS "genus" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "species" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "common_name" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "name" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "ecosystem_name" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "ecosystem_type" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "ecosystem_location" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "salinity" VARCHAR(255) DEFAULT '',
ADD COLUMN IF NOT EXISTS "climate" VARCHAR(255) DEFAULT '';
