ALTER TABLE fish
DROP COLUMN IF EXISTS genus,
DROP COLUMN IF EXISTS species,
DROP COLUMN IF EXISTS common_name,
DROP COLUMN IF EXISTS name,
DROP COLUMN IF EXISTS ecosystem_name,
DROP COLUMN IF EXISTS ecosystem_type,
DROP COLUMN IF EXISTS ecosystem_location,
DROP COLUMN IF EXISTS salinity,
DROP COLUMN IF EXISTS climate;
